### ISSUE TITLE
command line argument is required

### ISSUE THREAD

**Issue by tiangangzhou** [sillybun/vim-autodoc#1]
My program should add some command line arguments to execute, but this plugin can't provide argument. I'm supposed that this feature is useful.

![image](https://user-images.githubusercontent.com/24786426/41583236-62396764-73d6-11e8-9fe0-5be978ea829e.png)

**Comment by sillybun** [comment]
Actually, this plugin support command line argument. Just put your argument behind the Plugin Command.
For example, You can use the command:
```
:RecordParameter --walkers_evolve WALKER_EVOLVE
```

**Comment by tiangangzhou** [comment]
It will be better if you could add it to the documentation. Thank you!😄

**Comment by sillybun** [comment]
Sorry. I'm too busy preparing for my final exam.
